# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\administratorregistration.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from http.client import OK
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="attendance",
  port=3307
)


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(792, 670)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color:rgb(54,54,54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 10, 348, 65))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("\n"
"color:rgb(231, 251, 255)")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.registered = QtWidgets.QPushButton(Dialog)
        self.registered.setGeometry(QtCore.QRect(140, 520, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.registered.setFont(font)
        self.registered.setStyleSheet("background-color:rgb(31, 54, 24);\n"
"color:rgb(165, 251, 255)\n"
"\n"
"")
        self.registered.setObjectName("registered")
        self.confirmpassword = QtWidgets.QLineEdit(Dialog)
        self.confirmpassword.setGeometry(QtCore.QRect(360, 410, 371, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirmpassword.setFont(font)
        self.confirmpassword.setStyleSheet("background-color:rgb(221, 255, 254)")
        self.confirmpassword.setText("")
        self.confirmpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpassword.setObjectName("confirmpassword")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(60, 380, 261, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(165, 251, 255)")
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 171, 57))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(165, 251, 255)")
        self.label_2.setObjectName("label_2")
        self.firstname = QtWidgets.QLineEdit(Dialog)
        self.firstname.setEnabled(True)
        self.firstname.setGeometry(QtCore.QRect(360, 90, 371, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.firstname.setFont(font)
        self.firstname.setStyleSheet("background-color:rgb(221, 255, 254)")
        self.firstname.setText("")
        self.firstname.setObjectName("firstname")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 170, 161, 59))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(165, 251, 255)")
        self.label_3.setObjectName("label_3")
        self.lastname = QtWidgets.QLineEdit(Dialog)
        self.lastname.setGeometry(QtCore.QRect(360, 170, 371, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lastname.setFont(font)
        self.lastname.setStyleSheet("background-color:rgb(221, 255, 254)")
        self.lastname.setText("")
        self.lastname.setObjectName("lastname")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 240, 181, 59))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(165, 251, 255)")
        self.label_4.setObjectName("label_4")
        self.username = QtWidgets.QLineEdit(Dialog)
        self.username.setGeometry(QtCore.QRect(360, 240, 371, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setStyleSheet("background-color:rgb(221, 255, 254)")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(360, 320, 371, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgb(221, 255, 254)")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(80, 320, 211, 59))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(165, 251, 255)")
        self.label_5.setObjectName("label_5")

        self.registered.clicked.connect(self.regist)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Registration Form"))
        self.registered.setText(_translate("Dialog", "Click here to Register"))
        self.label_6.setText(_translate("Dialog", "Confirm password:"))
        self.label_2.setText(_translate("Dialog", "First name:"))
        self.label_3.setText(_translate("Dialog", "Last name:"))
        self.label_4.setText(_translate("Dialog", "Username:"))
        self.label_5.setText(_translate("Dialog", "Password:"))

    
    def regist(self):
        firstname = self.firstname.text()
        lastname=self.lastname.text()
        username = self.username.text()
        password = self.password.text()
        confirmpassword = self.confirmpassword.text()
        mycursor = mydb.cursor()
        checkUserNamesql = f'SELECT * FROM administrator WHERE username ="{username}"'
        mycursor.execute(checkUserNamesql)
        myresult = mycursor.fetchall()
        
        
        if (len(myresult) == 0):
            if (password == confirmpassword):
                sql = "INSERT INTO administrator (first_name, last_name, username, password) VALUES ('"+firstname+"', '"+lastname+"', '"+username+"', '"+password+"')"
                mycursor.execute(sql)
                mydb.commit()
                msg=QMessageBox()
                msg.setText("Registration successful")
                msg.setWindowTitle("show info")
                msg.setStandardButtons(QMessageBox.Ok)
                retval=msg.exec_()
                if OK:
                    from administrator import Ui_Dialog
                    Dialog = QtWidgets.QDialog()
                    ui = Ui_Dialog()
                    ui.setupUi(Dialog)
                    X=Dialog.exec()  
                
            else: 
                msg=QMessageBox()
                msg.setText("Password and confirm password need to be same.")
                msg.setWindowTitle("error")
                msg.setStandardButtons(QMessageBox.Ok)
                retval=msg.exec_()
        else: 
            # self.popup( "Username already registered.")
            msg=QMessageBox()
            msg.setText("Username already registered.")
            msg.setWindowTitle("error")
            msg.setStandardButtons(QMessageBox.Ok)
            retval=msg.exec_()

      

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
